// C NELSON 2020
/* Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose 
values do not exceed four million,
 find the sum of the even-valued terms.
(Answer = 4613732) */

// solution uses bitwise AND to test least significant bit

using System;
using System.Diagnostics;

namespace Euler02name
{
    class Euler02
    {
        static void Main(string[] args)
        {
            int n1 = 1;
            int n2 = 0;
            int n3 = 0;
            int finalAnswer = 0;

            var watch = new System.Diagnostics.Stopwatch();
            watch.Start();

            while (n3 < 4000000)
            {
                n3 = n1 + n2;
                if ((n3 & 1) != 1) // is even
                {
                    finalAnswer += n3;
                }
                n1 = n2;
                n2 = n3;
            }

            watch.Stop();
            
            Console.WriteLine("Answer:\t{0}", finalAnswer);
            Console.WriteLine("Took:\t{0} ticks", watch.ElapsedTicks);
            Console.WriteLine("Took:\t{0} ms", watch.ElapsedMilliseconds);
        }
    }
}