#Each new term in the Fibonacci sequence is
#generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence
#whose values do not exceed four million, find the
#sum of the even-valued terms.
# (Answer = 4613732)

# uses bitwise AND
# ~ 16000 nanoseconds

import time
start = time.perf_counter_ns()

i = 1
j = 2
total = 0
while i <= 4000000:
    if (i & 1 != 1):
        total += i 
    i, j = j, i + j

duration = time.perf_counter_ns() - start
print(total)
print("Took: %s nanoseconds" % (duration))

    
    
