% C NELSON 2020
% Each new term in the Fibonacci sequence is generated by
% adding the previous two terms.
% By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose
% values do not exceed four million,
% find the sum of the even-valued terms.
% (Answer = 4613732)
% 
% uses bitwise AND (band) to test least significant bit

-module(euler02).
-import(lists,[append/2, sum/1]).
-export([start/0, loop/3]).

start() ->
    List1 = [],
    loop(0, 1, List1).

loop(N1, N2, L1) when N2 < 4000000 ->
    if (N2 band 1)=/=1 ->
        NewList = lists:append(L1, [N2]);
    true ->
        NewList = L1
    end,
    loop(N2, N1 + N2, NewList);

loop(N1, N2, L1) when N2 > 4000000 ->
    FinalAnswer = sum(L1),
    io:format("Answer: ~w~n", [FinalAnswer]).