// C NELSON
{ Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose 
values do not exceed four million,
 find the sum of the even-valued terms.
(Answer = 4613732) }

// solution uses bitwise AND to test least significant bit

program Euler02;

    uses sysutils;

    var
        n1 : longint = 1;
        n2 : longint = 0;
        n3 : longint = 0;
        finalAnswer : longint = 0;
        tic, toc, timeElapsed: TDateTime;

begin

    tic := Now;

    while n3 < 4000000 do
        begin
            n3 := n1 + n2;
            if (n3 and 1 <> 1) then
                finalAnswer := finalAnswer + n3;
            n1 := n2;
            n2 := n3;
        end;
    
    toc := Now;
    timeElapsed := toc - tic;

    writeln('Answer:', #9, finalAnswer);
    writeln('Took:', #9, timeElapsed :0:6, ' seconds');

end.
