-- C NELSON 2020
--[[ Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose 
values do not exceed four million,
 find the sum of the even-valued terms.
(Answer = 4613732) --]]

-- solution uses modulo operator (lua v5.1 doesnt support bitwise AND)

n1 = 1
n2 = 0
n3 = 0
finalanswer = 0

tic = os.clock()

while (n3 < 4000000) do
    n3 = n1 + n2
    if (n3 % 2 == 0) then
        finalanswer = finalanswer + n3
    end
    n1 = n2
    n2 = n3
end

toc = os.clock()
timeElapsed = toc - tic

print(string.format("Answer:\t%s", finalanswer))
print(string.format("Took:\t%.6f seconds", timeElapsed))