' C NELSON 2020
' Each new term in the Fibonacci sequence is generated by 
' adding the previous two terms. 
' By starting with 1 and 2, the first 10 terms will be:
' 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
' By considering the terms in the Fibonacci sequence whose
' values do not exceed four million,
' find the sum of the even-valued terms.
' (Answer = 4613732)

' solution uses bitwise AND to test least significant bit

Module Euler02
    Sub Main( )

        Dim n1 as Integer = 1
        Dim n2 as Integer = 0
        Dim n3 as Integer = 0
        Dim finalAnswer As Integer = 0

        Dim tic As System.Diagnostics.Stopwatch = System.Diagnostics.Stopwatch.StartNew()

        While n3 < 4000000 
            n3 = n1 + n2
            If (n3 And 1) <> 1 Then
                finalAnswer += n3
            End If
            n1 = n2
            n2 = n3
        End While

        Dim timeElapsed = tic.Elapsed.TotalMilliseconds

        System.Console.WriteLine("Answer:" + vbtab + finalAnswer.ToString())
        System.Console.WriteLine("Took:" + vbtab + timeElapsed.ToString() + " ms")

    End Sub
End Module
