# C NELSON 2020
=begin
 Each new term in the Fibonacci sequence is generated by 
 adding the previous two terms. 
 By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose 
 values do not exceed four million,
 find the sum of the even-valued terms.
 (Answer = 4613732)
=end

# Solution uses bitwise AND to test least significant bit

n1 = 1
n2 = 0
n3 = 0
finalAnswer = 0

tic = Time.now

while n3 < 4000000 do
    n3 = n1 + n2
    if n3 & 1 != 1
        finalAnswer += n3
    end
    n1 = n2
    n2 = n3
end

toc = Time.now
timeElapsed = toc - tic

print "Answer:\t" + finalAnswer.to_s
print "\nTook:\t%.6f" % timeElapsed

