      * C NELSON 2020
      * Each new term in the Fibonacci sequence is generated by
      * adding the previous two terms.
      * By starting with 1 and 2, the first 10 terms will be:
      * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
      * By considering the terms in the Fibonacci sequence whose
      * values do not exceed four million,
      * find the sum of the even-valued terms.
      * (Answer = 4613732)
      *
      * solution uses bitwise AND to test least significant bit

       IDENTIFICATION DIVISION.
       PROGRAM-ID. Euler02.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.

       01  N1      PIC 9(8) VALUE 1.
       01  N2      PIC 9(8) VALUE 0.
       01  N3      PIC 9(8) VALUE 0.
       01  RES     PIC 9(8) VALUE 0.
       01  REM     PIC 9(2) VALUE 0.
       01  FINALANSWER      PIC 9(8) VALUE 0.

       01  START-TIME      PIC 9(2) VALUE 0.
       01  END-TIME        PIC 9(2) VALUE 0.
       01  DURATION        PIC 9(2) VALUE 0.

       01  WS-CURRENT-DATE-DATA.
           05  WS-CURRENT-DATE.
               10  WS-CURRENT-YEAR         PIC 9(04).
               10  WS-CURRENT-MONTH        PIC 9(02).
               10  WS-CURRENT-DAY          PIC 9(02).
           05  WS-CURRENT-TIME.
               10  WS-CURRENT-HOURS        PIC 9(02).
               10  WS-CURRENT-MINUTE       PIC 9(02).
               10  WS-CURRENT-SECOND       PIC 9(02).
               10  WS-CURRENT-MILLISECONDS PIC 9(02).

       PROCEDURE DIVISION.
       MAIN-PROCEDURE.

           MOVE FUNCTION CURRENT-DATE to WS-CURRENT-DATE-DATA
             SET START-TIME TO WS-CURRENT-MILLISECONDS.

           PERFORM PARA-A WITH TEST BEFORE UNTIL N3>4000000.

           MOVE FUNCTION CURRENT-DATE to WS-CURRENT-DATE-DATA
             SET END-TIME TO WS-CURRENT-MILLISECONDS.

           SUBTRACT END-TIME FROM START-TIME GIVING DURATION.

           DISPLAY "Answer:    " FINALANSWER.
           DISPLAY "Duration:  " DURATION "ms".

           STOP RUN.

           PARA-A.
           COMPUTE N3 = N1 + N2.
           DIVIDE N3 BY 2 GIVING RES REMAINDER REM.
           IF REM = 0 THEN
               ADD N3 TO FINALANSWER GIVING FINALANSWER
           END-IF.
           SET N1 TO N2.
           SET N2 TO N3.

       END PROGRAM Euler02.
